/*
 * This source file was generated by the Gradle 'init' task
 */
package qkart_automation;

import java.io.IOException;
import java.lang.reflect.Method;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeMethod;
import com.aventstack.extentreports.MediaEntityBuilder;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.model.Media;



public class BaseTest {

    WebDriver driver;

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s",
                        String.valueOf(java.time.LocalDateTime.now()), type, message, status));
    }
    
    @BeforeMethod(alwaysRun = true)
    public void beforeTestMethod(Method m){
        ExtentReportManager.startTest(m.getName());
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        DriverFactory.setDriver(driver);
    }

    @AfterMethod(alwaysRun = true)
    public void afterTestMethod(ITestResult iTestResult) throws IOException{
        if(iTestResult.getStatus() == ITestResult.SUCCESS){
            ExtentReportManager.log(Status.PASS, "Test Case Pass");
        }
        else if(iTestResult.getStatus() == ITestResult.FAILURE){
            Media media = MediaEntityBuilder.createScreenCaptureFromPath(Wrappers.capture(driver)).build();
            ExtentReportManager.log(Status.FAIL, "Test Case Failed", media);
        }
        else{
            ExtentReportManager.log(Status.SKIP, "Test Case Skipped");
        }

        ExtentReportManager.endTest();
        DriverFactory.removeDriver();
    }

    @AfterSuite(alwaysRun = true)
    public void endTestSuite(){
        ReportSingleton.getExtentReport().flush();
    }



}
